spring.application.name=api-gateway

server.port=8085

# =================================
# EUREKA
# =================================

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

# =================================
# GATEWAY ROUTES
# =================================

spring.cloud.gateway.server.webmvc.routes[0].id=notas-service

spring.cloud.gateway.server.webmvc.routes[0].uri=lb://NOTAS-SERVICE

spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/notas/**